### ISSUE TITLE
Change outputs in STATIONS() function

### ISSUE THREAD

**Issue by jongoetz** [bcgov/tidyhydat#6]
To make the metadata table more user-friendly, I suggest changing the STATIONS() table with the following. 

HYD_STATUS | A = ACTIVE; D = DISCONTINUED
SED_STATUS | A = ACTIVE; D = DISCONTINUED
RHBN | 0 = FALSE; 1 = TRUE
REAL_TIME | 0 = FALSE; 1 = TRUE

REGIONAL_OFFICE_ID |   replace with REGIONAL_OFFICE text from look-up table
CONTRIBUTOR_ID |   replace with CONTRIBUTOR text from look-up table
OPERATOR_ID |   replace with OPERATOR text from look-up table
DATUM_ID |   replace with DATUM text from look-up table

The HYDAT package uses the following to convert the the first 4 listed above, which could be applied.
metadata$RHBN <- ifelse(metadata$RHBN==1, TRUE, FALSE)
  metadata$REAL_TIME <- ifelse(metadata$REAL_TIME==1, TRUE, FALSE)
  metadata$HYD_STATUS <- ifelse(metadata$HYD_STATUS=="A","ACTIVE", 
                                ifelse(metadata$HYD_STATUS=="D", "DISCONTINUED", NA))
  metadata$SED_STATUS <- ifelse(metadata$SED_STATUS=="A","ACTIVE", 
ifelse(metadata$SED_STATUS=="D", "DISCONTINUED", NA))

**Comment by boshek** [comment]
Also applies to `ANNUAL_STATISTICS` symbol column:

https://github.com/bcgov/tidyhydat/blob/6ae2de6446f5584c254783b7a444412ba09772a0/R/ANNUAL_STATISTICS.R#L101

**Comment by boshek** [comment]
I think this makes sense for the 0 and 1 or the A and D values. For the others I think we are doing too much processing and it gets the output away from hydat in a way that isn't helpful.  This list:

REGIONAL_OFFICE_ID | replace with REGIONAL_OFFICE text from look-up table
CONTRIBUTOR_ID | replace with CONTRIBUTOR text from look-up table
OPERATOR_ID | replace with OPERATOR text from look-up table
DATUM_ID | replace with DATUM text from look-up table

is now provided by these functions:

- `AGENCY_LIST`
- `DATUM_LIST`
- `REGIONAL_OFFICE_LIST`

Then I think using dplyr tools like this:
```
hydat = "H:/Hydat.sqlite3"
STATIONS(STATION_NUMBER = "ALL", PROV_TERR_STATE_LOC = "PE", hydat_path = hydat) %>%
left_join(AGENCY_LIST(hydat), by = c("CONTRIBUTOR_ID" = "AGENCY_ID"))
```

will work fine. I made these functions rather than internal data because they are likely to change meaning `tidyhydat` is always matched closely to hydat. 

With respect to `RHBN`, `REAL_TIME`, `HYD_STATUS` and `SED_STATUS`, those aren't likely to change so I have hard-wired thsoe into `STATIONS`.

**Comment by jongoetz** [comment]
Looks great. Thanks!
 I had one small hiccup with the REGIONAL_OFFICE_LIST function as below.  The STATIONS()  REGIONAL_OFFICE_ID's are characters and the REGIONAL_OFFICE_LIST() ID's are integers, so I had to add an additional step of mutating the STATIONS() ID into an integer before left_join-ing. All other ID's (contributor, datum, etc) are integers in both.  A suggestion would be to make the STATIONS() office ID an integer to match the rest, if possible.

```
STATIONS(STATION_NUMBER = "ALL", PROV_TERR_STATE_LOC = "PE", hydat_path = hydat) %>%
left_join(REGIONAL_OFFICE_LIST(hydat), by = c("REGIONAL_OFFICE_ID" = "REGIONAL_OFFICE_ID"))
```
```
Error in left_join_impl(x, y, by$x, by$y, suffix$x, suffix$y, check_na_matches(na_matches)) : 
  Can't join on 'REGIONAL_OFFICE_ID' x 'REGIONAL_OFFICE_ID' because of incompatible types (integer / character)
```

**Comment by boshek** [comment]
Will do. I'll add to the devel branch and when I get enough changes I'll do version bump.
